# Generated by Django 4.2.7 on 2023-12-03 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('product_url', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField()),
                ('article', models.CharField(max_length=64)),
                ('ean_13', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('min_rec_price', models.FloatField(blank=True, null=True)),
                ('rec_price', models.FloatField()),
                ('category_id', models.FloatField()),
                ('ozon_name', models.CharField(max_length=256)),
                ('name_1c', models.CharField(max_length=256)),
                ('wb_name', models.CharField(max_length=256)),
                ('ozon_article', models.CharField(max_length=64)),
                ('wb_article', models.CharField(max_length=64)),
                ('ym_article', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_of_agreement', models.IntegerField()),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerprice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='DealerProductStausHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_datetime', models.DateTimeField(auto_now_add=True)),
                ('status_type', models.CharField(choices=[('ds', 'Рекомендательная модель'), ('manual', 'Поиск в ручную'), ('none', 'Не размечена')], default='none', max_length=6)),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerprice')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.dealerproductvariants')),
            ],
        ),
        migrations.CreateModel(
            name='DealerProductStausChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('true', 'Подтвердить'), ('false', 'Отклонить'), ('none', 'Отложить')], default='none', max_length=5)),
                ('status_datetime', models.DateTimeField(auto_now_add=True)),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerprice')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='DealerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('key', models.ManyToManyField(to='api.dealerprice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
