# Generated by Django 4.2.7 on 2023-11-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DealerPrice',
            fields=[
                ('product_key', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('product_url', models.CharField(max_length=256)),
                ('product_name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=64)),
                ('ean_13', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('cost', models.PositiveIntegerField()),
                ('min_rec_price', models.PositiveIntegerField()),
                ('rec_price', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('ozon_name', models.CharField(max_length=64)),
                ('name_1c', models.CharField(max_length=64)),
                ('wb_name', models.CharField(max_length=64)),
                ('ozon_article', models.CharField(max_length=64)),
                ('wb_article', models.CharField(max_length=64)),
                ('ym_article', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DealerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerprice')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
