# Generated by Django 4.2.7 on 2023-11-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.PositiveIntegerField(),
        ),
    ]
