# Generated by Django 4.2.7 on 2023-11-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerproduct')),
                ('product_id', models.ManyToManyField(to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='DealerProductStausChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('true', 'Подтвердить'), ('false', 'Отклонить'), ('none', 'Отложить')], max_length=5, null=True)),
                ('status_datetime', models.DateTimeField(auto_now_add=True)),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerproduct')),
            ],
        ),
        migrations.CreateModel(
            name='DealerProductMapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealer')),
                ('dealer_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dealerproduct')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
