# Generated by Django 4.2.7 on 2023-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dealer_name_alter_dealerprice_product_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerproductstaushistory',
            name='status_type',
            field=models.CharField(choices=[('ds', 'Рекомендательная модель'), ('manual', 'Поиск в ручную'), ('none', 'Не размечен'), ('aside', 'Отложенный'), ('cancel', 'Сброшенный')], db_index=True, default='none', max_length=6),
        ),
    ]
