# Generated by Django 4.2.7 on 2023-12-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dealerproductstaushistory_status_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerproductstauschange',
            name='status',
            field=models.CharField(choices=[('approve', 'Подтвердить'), ('disapprove', 'Отклонить'), ('aside', 'Отложить'), ('none', 'Не определено')], db_index=True, default='aside', max_length=10),
        ),
    ]
