# Generated by Django 4.2.7 on 2023-12-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dealerproductstauschange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerproductstauschange',
            name='status',
            field=models.CharField(choices=[('approve', 'Подтвердить'), ('disapprove', 'Отклонить'), ('aside', 'Отложить'), ('none', 'Не определено')], db_index=True, default='none', max_length=10),
        ),
    ]
