# Generated by Django 4.2.7 on 2023-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dealerproductstauschange_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprice',
            name='product_name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
