# Generated by Django 4.2.7 on 2023-12-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dealerprice_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprice',
            name='product_name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
