# Generated by Django 4.2.7 on 2023-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dealerprice_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerproductstauschange',
            name='status',
            field=models.CharField(choices=[('approve', 'Подтвердить'), ('disapprove', 'Отклонить'), ('aside', 'Отложить'), ('none', 'Не определено')], db_index=True, default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='dealerproductstaushistory',
            name='status_type',
            field=models.CharField(choices=[('ds', 'Рекомендательная модель'), ('manual', 'Поиск в ручную'), ('none', 'Не размечен'), ('aside', 'Отложенный'), ('cancel', 'Сброшенный')], db_index=True, default='none', max_length=12),
        ),
    ]
