name: Run tests

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main
    - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependenciesa
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          touch .env

          echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env
          echo DB_ENGINE=${{ secrets.DB_ENGINE }} >> .env
          echo DB_NAME=${{ secrets.DB_NAME }} >> .env
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB_PORT=${{ secrets.DB_PORT }} >> .env

          python manage.py test api.tests --verbosity=2