name: Django migrations Check

on:
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - main
    - dev

jobs:
  django-migrations-check:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run migrations check
        run: |
          touch .env

          echo SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} >> .env

          python manage.py makemigrations --check --dry-run
